<?xml version="1.0" encoding="utf-8"?>
<section xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:db="http://docbook.org/ns/docbook" xml:id="ug.perfcake-features.exit-codes" version="7.0">
   <title>Exit codes</title>
   <para>When PerfCake terminates normally, the exit code returned to the operating system is 0 as
      usual. In some cases and to ease automation, there might be a non zero return code depending
      on the situation. In the following table you can find the codes and their root
         causes.<footnote><para>In Linux systems, you can obtain the exit code from the <code>$?</code>
            environment property.</para></footnote></para>
   <table frame="all">
      <title>PerfCake Exit Codes</title>
      <tgroup cols="2">
         <colspec colname="c1" colnum="1" colwidth="0.1*" align="center"/>
         <colspec colname="c2" colnum="2" colwidth="0.9*" align="justify"/>
         <thead>
            <row>
               <entry align="left">Exit Code</entry>
               <entry align="left">Root Cause</entry>
            </row>
         </thead>
         <tbody>
            <row>
               <entry>1</entry>
               <entry>No scenario was specified on the command line or via the system
                  property.</entry>
            </row>
            <row>
               <entry>2</entry>
               <entry>Wrong parameters on the command line.</entry>
            </row>
            <row>
               <entry>3</entry>
               <entry>It was not possible to find, parse or load the scenario.</entry>
            </row>
            <row>
               <entry>4</entry>
               <entry>There was a general error during execution of the scenario. This can be
                  caused by incorrect or incompatible configuration parameters.</entry>
            </row>
            <row>
               <entry>5</entry>
               <entry>Some responses to messages did not pass validation.</entry>
            </row>
            <row>
               <entry>6</entry>
               <entry>There were blocked threads after the test execution that was not possible
                  to terminate cleanly. This can be caused by hanging connections or deadlocks in
                  the application under test.</entry>
            </row>
            <row>
               <entry>7</entry>
               <entry>There was an error while replaying a provided test record.</entry>
            </row>
            <row>
               <entry>8</entry>
               <entry>The user requested help/usage information with a command line option and it
                  was printed.</entry>
            </row>
         </tbody>
      </tgroup>
   </table>
</section>
